apiVersion: v2
name: "mesh"
description: "GraphQL Mesh gateway for learn-go, learn-python, and learn-rust services"
type: application
version: "0.1.0" # {"$imagepolicy": "playground:mesh-policy:tag"}
appVersion: "0.1.0" # {"$imagepolicy": "playground:mesh-policy:tag"}
maintainers:
  - name: "Daniel Ramirez <dxas90@gmail.com>"
